name: test workflow

on:
 workflow_dispatch:
   inputs:
     language:
      required: true
jobs:
  print:
   runs-on: ubuntu-latest
   steps:
  - run: | 
      echo "ENV: ${{ github.event.inputs.language }}"
