name: test workflow

on:
 workflow_dispatch:
   inputs:
     language: abc
      required: true
jobs:
  runs-on: ubuntu-latest
    steps:
  - run: | 
      echo "ENV: ${{ github.event.inputs.language }}"
